# Generated by Django 6.0.6 on 2026-07-02 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='specialists/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='booking.specialist')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
